name: lando-gatsby-drupal

recipe: drupal9
config:
  via: nginx
  webroot: CMS
  drush: false
  xdebug: false
  composer_version: '2.0.7'

services:
  appserver:
    build:
      - cd CMS && composer install
  gatsbyServer:
    type: node:14
    ssl: true
    overrides:
      volumes:
        - ./server:/app
      ports:
        - '8000'
    globals:
      gatsby-cli: "2.19.3"
      yarn: "1.22.17"
    run:
      - echo "Installing Gatsby with yarn."
      - yarn install

  appserver_nginx:
    ssl: true
    sslExpose: true
    type: nginx
    build_as_root:
      - cp /app/conf/nginx/drupal.lgd.lndo.site.conf /opt/bitnami/nginx/conf/vhosts/.
      - cp /app/conf/nginx/gatsbydrupal.lgd.lndo.site.conf /opt/bitnami/nginx/conf/vhosts/.
  pma:
    type: phpmyadmin:4.6
  database:
    type: mysql:5.7
    creds:
      user: admin
      password: admin
      database: drupal
# builds gatsby on lando start but is not needed because database is not yet ready..
# Use this if gatsby is on its own and not part of a lando build w/ drupal
#events:
#  post-start:
#    - gatsbyServer: echo "Building the Gatsby site from Drupal.  --- pending"
#    - gatsbyServer: gatsby build
#    - gatsbyServer: rm -rf gatsbydrupal/* && cp -R server/public/* gatsbydrupal
#    - gatsbyServer: gatsby develop --host 0.0.0.0

proxy:
  gatsbyServer:
    - gatsby.server.lndo.site:8000
  appserver_nginx:
    - drupal.lgd.lndo.site
    - gatsbydrupal.lgd.lndo.site

tooling:
  yarn:
    service: gatsbyServer
  npm:
    cmd: Nope, try `lando yarn` instead.
    service: gatsbyServer
  node:
    service: gatsbyServer
  gatsby:
    service: gatsbyServer
  gatsbyBuild:
    service: gatsbyServer
    user: root
    description: runs gatsby build and copies files to gatsbydrupal
    cmd: gatsby build
  deployGatsby:
    service: appserver_nginx
    description: move files from gatsby build over to gatsbydrupal for deployment
    cmd: rm -rf gatsbydrupal/* && cp -R server/public/* gatsbydrupal
  gatsbyDevServerStart:
    service: gatsbyServer
    description: start the gatsby dev server
    cmd: gatsby develop --host 0.0.0.0
