name: lando-gatsby-drupal

recipe: drupal9
config:
  via: nginx
  webroot: CMS
  drush: false
  xdebug: false
  composer_version: '2.0.7'

services:
  appserver:
    build:
      - cd CMS && composer install
  gatsbyServer:
    type: node:14
    port: 8000
    ssl: true
    globals:
      gatsby-cli: "2.19.3"
      yarn: "1.22.17"
    run:
      - echo "Installing Gatsby with yarn."
      - cd server && yarn install
    cmd: cd server && gatsby develop --host 0.0.0.0

  appserver_nginx:
    ssl: true
    sslExpose: true
    type: nginx
    build_as_root:
      - cp /app/conf/nginx/drupal.lgd.lndo.site.conf /opt/bitnami/nginx/conf/vhosts/.
      - cp /app/conf/nginx/gatsbydrupal.lgd.lndo.site.conf /opt/bitnami/nginx/conf/vhosts/.
  pma:
    type: phpmyadmin:4.6
  database:
    type: mysql:5.7
    creds:
      user: admin
      password: admin
      database: drupal

events:
  post-start:
    - gatsbyServer: echo "Building the Gatsby site from Drupal."
    - gatsbyServer: cd server && gatsby build
    - gatsbyServer: rm -rf gatsbydrupal/* && cp -R server/public/* gatsbydrupal
    - gatsbyServer: cd server && GATSBY_GRAPHQL_IDE=playground gatsby develop

proxy:
  gatsbyServer:
    - gatsby.graph.lndo.site:8000
  appserver_nginx:
    - drupal.lgd.lndo.site
    - gatsbydrupal.lgd.lndo.site

tooling:
  yarn:
    service: gatsbyServer
  npm:
    cmd: Nope, try `lando yarn` instead.
    service: gatsbyServer
  node:
    service: gatsbyServer
  gatsby:
    service: gatsbyServer
  gatsby:build:
    cmd: gatsby build && cd ../ && rm -rf gatsbydrupal/* && cp -R server/public/* gatsbydrupal
  gatsby:start:
    cmd: gatsby develop --host 0.0.0.0
